language: python

install:
  - pip install .[test]

script:
  - pytest

deploy:
  provider: pypi
  username: "__token__"
  password:
    secure: QiEOaic5krYqZHAxrybem6TXOczgAzf6ImeeLW339ZiJXmoX3Ww/VlEjxkX1dP9x3eXklHwuyfOFZrq7RazGS44y0E9o+ubDmc20aDiv9hGRCMQbo9ucfIZFMm0RidycdUZBL2S4aTUxGGBsa4+5BWTM9FTJeMc1cGFLeFOaf0Pdc235A5zNZN8AkME6yJLR79s4g9qusYpwsvr+63oFxpf+8/NnFJdDVuq+mVyXcYPY9zoaJYWJi+IXpUUAp8UmWvIB8StXGcQvZdO0BEgCymJaUNapsC3geXbf+xBrgmFSBHT0Owl9MN9ukyTvc1C74DXhCZRtIBhObBYqdnuo8lj/rXV2uc3lBJD05eDFXExtcR7Os/hr9jdK8tTkPtTMfBN1kXp2xkZW7KJB/5iT6MN3mZWkPO3pDqpmz/tX3R29w27FxM4PUhIWO7BMqdcGz1iXHEflw4EGW060Z4u5yuxSyJRac0kPCja5LmAP1s6F2DKffe4TIzsm/BZJwRSraeI2MB806BrwXX8uZhKepZxWXKVPBJ+0rQqRHDZ/DVlZE4JHCIB7wljB/so+pCg2PYyfFWK2O12IcmQYVu/9c0g8ukf3gwDec0wk7Z7YlI4Sv9QeATxtGwJ/8mF4uOd79+MfqcZISNYHRXbdgaVsafE6eKJsa5B4imsCa1qusGg=
  on:
    distributions: sdist bdist_wheel
    repo: CrossNox/YouConfigMe
