language: python
install:
- pip install .[test]
script:
- pytest
deploy:
  provider: pypi
  username: __token__
  password:
    secure: HZBkgdKKwkpK8gTjGinz7EOlb2SblMrrn9edV8Q9zAr18MGv0Zo721SqzuGttx8fhQZEn+xw97n5V41GcLZcIAeQ/DH1UL+Sfdu/VxpdtUNGPj1d7pBO/LbjUnNAT6pMlg3ZUpdEPOYiQi1QeeGaHJVLDhzaLpQugcEuSFY064Ogg0R0+dPz7QV//sYYpm2XD3G9jIv9kzsfyda2PpnWqSQfOKiCiKH/IavoCArC8rGwhuIKN4/04jS2jlDzy//mfPbgJNiPPqEJj8sEF9CsRORGFw9Tq+oYpf6lMddfppucvrZ+qsN/8t9oR/Ofi/NTQbsjEGpuj/Joha9AzDKPNoGYT6k2ZEh/odKRdghjuItwwoRtcPpRZkjV68NvPq/us8OeFA1NhaO9QBPfjRAWj5Ukb8WFPcGIsQ5lIzQNkSgTG/ZqgNOxOMrcmpu7lNoN1IShWVHKJ+ka5njEqjWbwObMWWcYvR7PwXat2/TBWwbO8cFVJZGr21eBMrMOAumYHFV4QfKTCzn+DKk5opdJSsugIOM0KEPbJL5VX7DK4syj/7VM9uuS2NusF439fyAtayE7TVcvRc5Ipp2g/6FcG0YSfa9zj45L6Nb826Fl0HN6HxaPlnACbAlpBsCwHZwal7FF/WtN+fmQcN7pcq9FZcUcvJMFuPTuh6+Qsn2hGnM=
  on:
    distributions: sdist bdist_wheel
    repo: CrossNox/YouConfigMe
