[mypy]
python_version = 3.10
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
check_untyped_defs = True
disallow_any_generics = True
warn_redundant_casts = True
warn_unused_ignores = True
warn_unreachable = True
strict_equality = True
show_error_codes = True

# Ignore all test files by default
[mypy-tests.*]
ignore_errors = True

[mypy-tests.test_typing]
ignore_errors = False
