"""Type stubs for youconfigme"""

import logging
from pathlib import Path
from typing import (Any, Callable, Dict, List, Mapping, Optional, TypeVar,
                    Union, overload, TYPE_CHECKING)

if TYPE_CHECKING:
    from enum import Enum

    class ellipsis(Enum):
        Ellipsis = "..."

    Ellipsis = ellipsis.Ellipsis
else:
    ellipsis = type(Ellipsis)

T = TypeVar("T")

DEFAULT_SECTION: str
INI_FILE: str
DEFAULT_SEP: str

def config_logger(name: str) -> logging.Logger: ...

class ConfigItemNotFound(Exception): ...

class ConfigAttribute:
    def __init__(
        self,
        name: str,
        value: Optional[Any],
        section_name: Optional[str],
        sep: str = ...,
    ) -> None: ...
    @overload
    def __call__(
        self, default: ellipsis = ..., cast: None = ..., from_pass: bool = ...
    ) -> str: ...
    @overload
    def __call__(
        self, default: str, cast: None = ..., from_pass: bool = ...
    ) -> str: ...
    @overload
    def __call__(
        self, default: T, cast: None = ..., from_pass: bool = ...
    ) -> Union[T, str]: ...
    @overload
    def __call__(
        self,
        default: ellipsis = ...,
        cast: Callable[[str], T] = ...,
        from_pass: bool = ...,
    ) -> T: ...
    @overload
    def __call__(
        self, default: Any, cast: Callable[[str], T], from_pass: bool = ...
    ) -> T: ...
    def __getattr__(self, name: str) -> None: ...

class ConfigSection:
    def __init__(
        self, name: str, items: Optional[Mapping[str, Any]], sep: str = ...
    ) -> None: ...
    def __getattr__(self, val: str) -> ConfigAttribute: ...
    def __call__(
        self, default: Any = ..., cast: Optional[Callable[[str], Any]] = ...
    ) -> Any: ...
    def to_dict(self) -> Dict[str, str]: ...

FromItemsType = Union[str, Path, Mapping[str, Any], None]

class Config:
    def __init__(
        self,
        from_items: FromItemsType = ...,
        default_section: str = ...,
        sep: str = ...,
    ) -> None: ...
    def _init_from_mapping(self, mapping: Mapping[str, Any]) -> None: ...
    def _init_from_str(self, str_like: Union[str, Path]) -> None: ...
    def __getattr__(self, name: str) -> ConfigSection: ...
    def to_dict(self) -> Dict[str, Dict[str, str]]: ...
    def to_dotenv(self) -> str: ...

class AutoConfig(Config):
    def __init__(
        self, max_up_levels: int = ..., filename: str = ..., sep: str = ...
    ) -> None: ...
